export const FAILURE_CODES = [
  "CONFIG_INVALID",
  "ENVIRONMENT_MISSING_TOOL",
  "DEVICE_UNAVAILABLE",
  "BUILD_FAILED",
  "APP_LAUNCH_FAILED",
  "APP_CRASHED",
  "LOCATOR_NOT_FOUND",
  "LOCATOR_AMBIGUOUS",
  "ACTION_FAILED",
  "IDLE_TIMEOUT",
  "ACTIVITY_BEFORE_MISMATCH",
  "ACTIVITY_AFTER_MISMATCH",
  "EXPECT_ACTIVITY_FAILED",
  "EXPECT_ELEMENT_FAILED",
  "EXPECT_LOGCAT_FAILED",
  "COLLECTION_FAILED",
  "INTERNAL_ERROR"
] as const;

export type FailureCode = (typeof FAILURE_CODES)[number];
export type TapHoundExitCode = 1 | 2 | 3 | 4;

const EXIT_CODES = {
  CONFIG_INVALID: 2,
  ENVIRONMENT_MISSING_TOOL: 3,
  DEVICE_UNAVAILABLE: 3,
  BUILD_FAILED: 1,
  APP_LAUNCH_FAILED: 1,
  APP_CRASHED: 1,
  LOCATOR_NOT_FOUND: 1,
  LOCATOR_AMBIGUOUS: 1,
  ACTION_FAILED: 1,
  IDLE_TIMEOUT: 1,
  ACTIVITY_BEFORE_MISMATCH: 1,
  ACTIVITY_AFTER_MISMATCH: 1,
  EXPECT_ACTIVITY_FAILED: 1,
  EXPECT_ELEMENT_FAILED: 1,
  EXPECT_LOGCAT_FAILED: 1,
  COLLECTION_FAILED: 1,
  INTERNAL_ERROR: 4
} as const satisfies Record<FailureCode, TapHoundExitCode>;

export function exitCodeForFailure(failure: FailureCode): TapHoundExitCode {
  return EXIT_CODES[failure];
}
