import type { ExternalFlow } from "../../domain/external-flow.js";
import type { FailureCode } from "../../domain/failure.js";
import type { AdbPort, DeviceInfo } from "../../ports/adb.js";
import type { AlignPromptPort } from "../../ports/align-prompt.js";
import type {
  CameraProbePort,
  CameraProbeResult
} from "../../ports/camera-probe.js";
import { CameraProbeError } from "../../ports/camera-probe.js";
import type {
  ExternalFlowRegistry,
  WriteExternalFlowResult
} from "../../ports/external-flow-registry.js";

export class AlignError extends Error {
  public readonly code: FailureCode;
  public constructor(code: FailureCode, message: string) {
    super(message);
    this.name = "AlignError";
    this.code = code;
  }
}

export interface AlignServiceDeps {
  adb: AdbPort;
  probe: CameraProbePort;
  prompt: AlignPromptPort;
  registry: ExternalFlowRegistry;
}

export interface AlignCameraInput {
  projectRoot: string;
  deviceSerial?: string | undefined;
  force?: boolean | undefined;
  json: boolean;
  signal?: AbortSignal | undefined;
}

export interface AlignCameraWrittenResult {
  status: "written";
  exitCode: 0;
  flow: WriteExternalFlowResult & { name: string; steps: number };
  probe: CameraProbeResult;
  deviceSerial: string;
}

export interface AlignCameraCancelledResult {
  status: "cancelled";
  exitCode: 2;
}

export type AlignCameraResult =
  | AlignCameraWrittenResult
  | AlignCameraCancelledResult;

const FLOW_NAME = "camera/photo-capture";

function selectDevice(
  devices: readonly DeviceInfo[],
  requested?: string
): string | undefined {
  const online = devices.filter((device) => device.status === "device");
  if (requested !== undefined) {
    return online.find((device) => device.serial === requested)?.serial;
  }
  return online.length === 1 ? online[0]?.serial : undefined;
}

function buildFlow(
  probeResult: CameraProbeResult,
  deviceSerial: string
): ExternalFlow {
  const steps: ExternalFlow["steps"] = [
    { action: "wait", expectedActivity: probeResult.activityName },
    {
      action: "click",
      locator: { resourceId: probeResult.shutterResourceId },
      expectedActivity: probeResult.activityName
    }
  ];
  if (probeResult.confirmResourceId !== undefined) {
    steps.push({
      action: "click",
      locator: { resourceId: probeResult.confirmResourceId },
      expectedActivity: probeResult.confirmActivityName
        ?? probeResult.activityName
    });
  }
  return {
    version: 1,
    kind: "externalFlow",
    name: FLOW_NAME,
    description: `Auto-generated by \`taphound align camera\` for ${probeResult.packageName} on ${deviceSerial}`,
    escapedPackageName: probeResult.packageName,
    expectedEscapeActivity: probeResult.activityName,
    includes: [],
    steps
  };
}

export class AlignService {
  public constructor(private readonly deps: AlignServiceDeps) {}

  public async alignCamera(
    input: AlignCameraInput
  ): Promise<AlignCameraResult> {
    const devices = await this.deps.adb.devices(input.signal);
    const deviceSerial = selectDevice(devices, input.deviceSerial);
    if (deviceSerial === undefined) {
      throw new AlignError(
        "ALIGN_DEVICE_UNAVAILABLE",
        input.deviceSerial === undefined
          ? `Expected exactly one online device, found ${String(devices.filter((d) => d.status === "device").length)}`
          : `Requested device is not online: ${input.deviceSerial}`
      );
    }

    let probeResult: CameraProbeResult;
    try {
      probeResult = await this.deps.probe.probe({
        deviceSerial,
        ...(input.signal === undefined ? {} : { signal: input.signal })
      });
    } catch (error) {
      if (error instanceof CameraProbeError) {
        throw new AlignError(error.code, error.message);
      }
      throw error;
    }

    if (!input.json) {
      const confirmed = await this.deps.prompt.confirmWrite({
        values: probeResult,
        targetPath: `.taphound/flows/external/${FLOW_NAME}.json`
      });
      if (!confirmed) {
        return { status: "cancelled", exitCode: 2 };
      }
    }

    const flow = buildFlow(probeResult, deviceSerial);
    let writeResult: WriteExternalFlowResult;
    try {
      writeResult = await this.deps.registry.write({
        projectRoot: input.projectRoot,
        name: FLOW_NAME,
        flow,
        ...(input.force === undefined ? {} : { force: input.force })
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (/already exists/i.test(message)) {
        throw new AlignError(
          "ALIGN_FLOW_EXISTS",
          `External Flow already exists: ${FLOW_NAME} (use --force to overwrite)`
        );
      }
      throw error;
    }

    return {
      status: "written",
      exitCode: 0,
      flow: { ...writeResult, name: FLOW_NAME, steps: flow.steps.length },
      probe: probeResult,
      deviceSerial
    };
  }
}
